# This workflow triggers when a new release has been made.

name: OCI CLI Installation Testing

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version number ("latest" or "v1.35.0")'
        required: true
        default: latest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # NOTE: If this runs in an environment, set this value (where "MC-Action" is the environment name)
    # environment: MC-Action

    # The type of runner that the job will run on
    runs-on: macos-11
    steps:
      - name: Get Latest Release with Tag
        id: latestrelease
        run: |
          echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/oracle/oci-cli/releases/latest | jq '.tag_name' | sed 's/\"//g')"
      - name: Confirm Release Tag
        run: |
          echo ${{ steps.latestrelease.outputs.releasetag }}
      - name: Tag Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.latestrelease.outputs.releasetag }}
      - name: Run MacOS Installation Tests
        run: ./scripts/github_actions/mac_installation_tests.sh
