name: Bump Homebrew Formula

on:
  workflow_dispatch:

jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_API_TOKEN }}
          formula: oci-cli
